### ISSUE TITLE
'FileNotFoundError: [Errno 2] No such file or directory:' ... 'nbpresent.min.css'

### ISSUE THREAD

**Issue by nocibambi** [anaconda-graveyard/nbpresent#101]
I just freshly installed nbpresent with conda. When I try to run it I receive the following error:

```shell
$ nbpresent -i notebook_name.ipynb -o presentation_namehtml -f html
Traceback (most recent call last):
  File "/home/user_name/anaconda3/bin/nbpresent", line 11, in <module>
    load_entry_point('nbpresent==3.0.2', 'console_scripts', 'nbpresent')()
  File "/home/user_name/anaconda3/lib/python3.7/site-packages/nbpresent/export.py", line 60, in main
    export(**parser.parse_args().__dict__)
  File "/home/user_name/anaconda3/lib/python3.7/site-packages/nbpresent/export.py", line 24, in export
    output, resources = exp.from_filename(ipynb)
  File "/home/user_name/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/user_name/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/user_name/anaconda3/lib/python3.7/site-packages/nbpresent/exporters/html.py", line 40, in from_notebook_node
    with codecs.open(filename, mode, encoding="utf-8") as fp:
  File "/home/user_name/anaconda3/lib/python3.7/codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user_name/anaconda3/lib/python3.7/site-packages/nbpresent/static/nbpresent/css/nbpresent.min.css'
```

I checked the folder and there is not even a `css` folder. With pdf output I try the same error message (save the traceback path).

I am on ubuntu 18.04.

Any ideas?

**Comment by Ohtar10** [comment]
I'm also facing the same issue.

Tried with version 3.0.0 and the error no longer appear. However, in my particular case with my specific notebook, the html does not show anything in the browser.

I believe it's because it is unable to find some css files.
```
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 1.05ms
WARNING:tornado.access:404 GET /style.min.css.map (127.0.0.1) 9.84ms
WARNING:tornado.access:404 GET /style.min.css.map (127.0.0.1) 1.11ms
```
